# GET /sources/
source_list = '''[{"id": 21836, "url": "https://test.koordinates.com/services/api/v1/sources/21836/", "url_html": "https://test.koordinates.com/source/21836-nzdf-built-up-area-area-feature-shpzip/", "title": "nzdf-built-up-area-area-feature-SHP.zip", "type": "upload"}, {"id": 21838, "url": "https://test.koordinates.com/services/api/v1/sources/21838/", "url_html": "https://test.koordinates.com/source/21838-kx-nz-mainland-contours-topo-1-50k-shp-1zip/", "title": "kx-nz-mainland-contours-topo-1-50k-SHP (1).zip", "type": "upload"}, {"id": 21770, "url": "https://test.koordinates.com/services/api/v1/sources/21770/", "url_html": "https://test.koordinates.com/source/21770-nz-river-namesxls/", "title": "NZ-river-names.xls", "type": "upload"}, {"id": 21876, "url": "https://test.koordinates.com/services/api/v1/sources/21876/", "url_html": "https://test.koordinates.com/source/21876-lds-new-zealand-3layers-shpzip/", "title": "lds-new-zealand-3layers-SHP.zip", "type": "upload"}]'''
# GET /sources/21836/
source_detail = '''{"id": 21836, "url": "https://test.koordinates.com/services/api/v1/sources/21836/", "url_html": "https://test.koordinates.com/source/21836-nzdf-built-up-area-area-feature-shpzip/", "title": "nzdf-built-up-area-area-feature-SHP.zip", "type": "upload", "license": null, "publish_to_catalog_services": false, "permissions": "https://test.koordinates.com/services/api/v1/sources/21836/permissions/", "description": "Upload: nzdf-built-up-area-area-feature-SHP.zip", "description_html": "<p>Upload: nzdf-built-up-area-area-feature-SHP.zip</p>", "categories": [], "tags": [], "group": {"id": 371, "url": "https://test.koordinates.com/services/api/v1/groups/371/", "name": "GNZ Test Group", "country": "NZ"}, "metadata": null, "last_scanned_at": null, "scan_schedule": null, "options": {}}'''
# POST /sources/
source_create_arcgis = '''{"id": 58, "url": "https://test.koordinates.com/services/api/v1/sources/58/", "url_html": "https://test.koordinates.com/source/58-bobs-arcgis-10-server/", "title": "Bob's ArcGIS 10 Server", "type": "arcgis", "license": null, "publish_to_catalog_services": false, "permissions": "https://test.koordinates.com/services/api/v1/sources/58/permissions/", "description": "All of Bob's data", "description_html": "<p>All of Bob's data</p>", "categories": [], "tags": [], "user": {"id": 3, "url": "https://test.koordinates.com/services/api/v1/users/3/", "first_name": "Peter", "last_name": "Kay", "country": "NZ"}, "metadata": null, "last_scanned_at": null, "scan_schedule": null, "options": {}, "url_remote": "http://server.arcgisonline.com/ArcGIS/rest/services"}'''
source_create_arcgis_bad_remote = '''{"url_remote": ["Invalid URL: Can't resolve host."]}'''
source_create_upload_single = '''{}'''
source_create_upload_multiple = '''{}'''
source_create_upload_archive = '''{}'''
source_scan_list = '''[{"id": 41, "url": "https://test.koordinates.com/services/api/v1/sources/44/scans/41/", "status": "completed", "started_at": "2014-11-26T05:34:13.008217Z", "completed_at": "2014-11-26T05:34:18.842557Z", "change_counts": {"deleted": 0, "updated": 0, "added": 1}, "log": "https://test.koordinates.com/services/api/v1/sources/44/scans/41/log/", "source": "https://test.koordinates.com/services/api/v1/sources/44/"}]'''
source_scan_detail = '''{"id": 41, "url": "https://text.koordinates.com/services/api/v1/sources/44/scans/41/", "status": "completed", "started_at": "2014-11-26T05:34:13.008217Z", "completed_at": "2014-11-26T05:34:18.842557Z", "change_counts": {"deleted": 0, "updated": 0, "added": 1}, "log": "https://text.koordinates.com/services/api/v1/sources/44/scans/41/log/", "source": "https://text.koordinates.com/services/api/v1/sources/44/", "progress": 1.0}'''
source_scan_log = '''2014-11-26 18:34:18: Looking for possible datasources in 0/44/\n2014-11-26 18:34:18: Found 1 possible data sources\n2014-11-26 18:34:18: Scanning bad_nodata_value.tif as GTiff\n2014-11-26 18:34:18:     - valid GTiff\n2014-11-26 18:34:18: Scanning valid datasources for more information\n2014-11-26 18:34:18: Scanning bad_nodata_value.tif\n2014-11-26 18:34:18:   New data source created\n2014-11-26 18:34:18: Finishing up\n2014-11-26 18:34:18: Updating 1 new or changed datasets\n2014-11-26 18:34:18: Updating user interface\n2014-11-26 18:34:18: Finished!\n'''